"""Regenerate every number, table, and result figure used in paper/main.tex.

All quantities are computed from artifacts committed in this repository:

- outputs/<run>/samples.jsonl, generation_summary.csv, config.json
  (historical real-model pilot runs; re-scored with the current evaluator)
- outputs/simulated_ab/*/history.jsonl (simulated-target A/B)
- prompts/initial_population.csv (seed pool) and the legacy quality gates
  snapshotted from the `main` branch in legacy_quality_constraints.py
- tests/fixtures/attack_evaluator_calibration.json

Outputs:
    paper/generated/numbers.tex   \\newcommand macros used in the text
    paper/generated/*.tex         table bodies
    paper/figures/*.pdf           result figures

    python3 -B paper/scripts/make_paper_assets.py
"""

from __future__ import annotations

import csv
import importlib.util
import json
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
GEN = PAPER / "generated"
FIG = PAPER / "figures"
sys.path.insert(0, str(ROOT))
csv.field_size_limit(sys.maxsize)

from analysis.convergence import analyze_run  # noqa: E402
from evaluators import (  # noqa: E402
    DefensiveComplianceEvaluator,
    attack_progress,
    calibration_confusion_matrix,
)
from evolutionary_strategy import load_prompt_population  # noqa: E402
from quality_constraints import apply_quality_constraints  # noqa: E402

# Light-mode reference categorical slots (validated set; see dataviz palette).
BLUE, ORANGE, AQUA = "#2a78d6", "#eb6834", "#1baf7a"
INK, MUTED, GRID = "#0b0b0b", "#52514e", "#d9d8d4"

# Real-model pilot series: identical budget (mu=8, lambda=16, G=80, K=2).
PILOT_SERIES = [
    "real_fixed_filter_baseline_v6",
    "real_filter_v6",
    "real_filter_v7_dedup",
    "real_filter_v8_no_duplicate_rules",
    "main_v11_filter_fallback",
    "main_v15_multi_fallback",
    "main_v16_final",
    "main_v17_garbled_filter_fallback",
    "main_v18_grammar_exfil",
]
RUN_LABELS = {
    "real_fixed_filter_baseline_v6": "P0 (fixed)",
    "real_filter_v6": "P1",
    "real_filter_v7_dedup": "P2",
    "real_filter_v8_no_duplicate_rules": "P3",
    "main_v11_filter_fallback": "P4",
    "main_v15_multi_fallback": "P5",
    "main_v16_final": "P6",
    "main_v17_garbled_filter_fallback": "P7",
    "main_v18_grammar_exfil": "P8",
}


def fmt(value, digits=3):
    if value is None:
        return "--"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def pct(value, digits=1):
    return f"{100.0 * value:.{digits}f}\\%"


class Numbers:
    def __init__(self):
        self.items = {}

    def __setitem__(self, key, value):
        if not key.isalpha():
            raise ValueError(f"LaTeX macro names must be letters only: {key}")
        self.items[key] = value

    def write(self, path: Path):
        lines = ["% Generated by paper/scripts/make_paper_assets.py -- do not edit."]
        for key, value in sorted(self.items.items()):
            lines.append(f"\\newcommand{{\\{key}}}{{{value}}}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def load_legacy_gates():
    spec = importlib.util.spec_from_file_location(
        "legacy_quality_constraints", PAPER / "scripts" / "legacy_quality_constraints.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def seed_gate_audit(numbers: Numbers):
    legacy = load_legacy_gates()
    results = {}
    for name, gates in (("legacy", legacy.apply_quality_constraints), ("current", apply_quality_constraints)):
        seeds = load_prompt_population(str(ROOT / "prompts" / "initial_population.csv"))
        for prompt in seeds:
            prompt.output_prompts = ["controlled filtered output"]
            prompt.direct_output = "controlled direct output"
        reasons = gates(seeds)
        valid = int(sum(p.metrics["valid"] for p in seeds))
        results[name] = {"total": len(seeds), "valid": valid, "reasons": dict(reasons)}
    numbers["seedPoolSize"] = results["current"]["total"]
    numbers["seedValidLegacy"] = results["legacy"]["valid"]
    numbers["seedValidCurrent"] = results["current"]["valid"]
    numbers["seedGarbledLegacy"] = results["legacy"]["reasons"].get("garbled_tokens", 0)
    numbers["seedGarbledLegacyPct"] = pct(
        results["legacy"]["reasons"].get("garbled_tokens", 0) / results["legacy"]["total"]
    )
    return results


def seed_labels(numbers: Numbers):
    import ast

    structure, content = Counter(), Counter()
    with (ROOT / "prompts" / "initial_population.csv").open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            for label in ast.literal_eval(row["structure_labels"]):
                structure[label] += 1
            for label in ast.literal_eval(row["labels"]):
                content[label] += 1
    rows = []
    for kind, counter in (("Structure", structure), ("Content", content)):
        for label, count in counter.most_common():
            rows.append(f"{kind} & \\texttt{{{label.replace('_', chr(92) + '_')}}} & {count} \\\\")
    (GEN / "seed_labels.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
    return structure, content


def calibration(numbers: Numbers):
    fixtures = json.loads((ROOT / "tests" / "fixtures" / "attack_evaluator_calibration.json").read_text())
    if isinstance(fixtures, dict):
        fixtures = fixtures.get("fixtures", fixtures.get("items", []))
    report = calibration_confusion_matrix(DefensiveComplianceEvaluator(), fixtures)
    numbers["calibTotal"] = report["total"]
    numbers["calibCorrect"] = report["correct"]
    labels = report["labels"]
    rows = []
    for expected in labels:
        cells = [str(report["confusion_matrix"][expected][predicted]) for predicted in labels]
        rows.append(f"\\texttt{{{expected.replace('_', chr(92) + '_')}}} & " + " & ".join(cells) + " \\\\")
    (GEN / "calibration.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")


def rescored_label_mix(run_dirs, evaluator):
    labels = Counter()
    pattern_share = {}
    for run_dir in run_dirs:
        patterns = Counter()
        compliant = 0
        with (run_dir / "samples.jsonl").open(encoding="utf-8") as handle:
            for line in handle:
                row = json.loads(line)
                if row.get("kind") != "filtered" or row.get("status") != "valid":
                    continue
                result = evaluator.evaluate(row.get("text", ""))
                labels[result.label] += 1
                if result.label == "compliant":
                    compliant += 1
                    matched = result.metadata["signals"]["harmful_operational_patterns"]
                    if matched:
                        patterns[matched[0]] += 1
        pattern_share[run_dir.name] = (
            patterns.most_common(1)[0][1] / compliant if compliant and patterns else None
        )
    return labels, pattern_share


def operator_noop_share(run_dir: Path):
    path = run_dir / "generation_summary.csv"
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    attempts = sum(float(r.get("operator_attempts") or 0) for r in rows)
    noops = sum(float(r.get("operator_noops") or 0) for r in rows)
    return noops / attempts if attempts else None


def pilot(numbers: Numbers):
    evaluator = DefensiveComplianceEvaluator()
    run_dirs = [ROOT / "outputs" / name for name in PILOT_SERIES]
    results = [analyze_run(run_dir, evaluator, 5) for run_dir in run_dirs]
    labels, pattern_share = rescored_label_mix(run_dirs, evaluator)
    registry = json.loads((ROOT / "experiments" / "invalid_runs.json").read_text())
    quarantined = {Path(entry["path"]).name for entry in registry.get("runs", [])}

    table = []
    near_dup, noop_shares = [], []
    for run_dir, result in zip(run_dirs, results):
        config = json.loads((run_dir / "config.json").read_text())
        args = config["args"]
        gates = result["quality_gate_rejections_per_parent_slot"]
        nd = gates.get("near_duplicate", 0.0)
        other = float(sum(v for k, v in gates.items() if k != "near_duplicate"))
        near_dup.append(nd)
        noop = operator_noop_share(run_dir)
        if noop is not None:
            noop_shares.append(noop)
        label = RUN_LABELS[run_dir.name] + ("$^{\\dagger}$" if run_dir.name in quarantined else "")
        model = str(args.get("model"))
        model = {"dphn/Dolphin3.0-Llama3.1-8B": "Dolphin", "dolphin": "Dolphin"}.get(model, model)
        table.append(
            " & ".join(
                [
                    label,
                    model.replace("_", "\\_"),
                    str(args.get("filter_update_every") or 0),
                    str(result["filter_updates"]),
                    str(result["filtered_samples"]),
                    fmt(result["overall_compliance_rate"]),
                    fmt(result["early_quarter_compliance_rate"]),
                    fmt(result["late_quarter_compliance_rate"]),
                    fmt(result["first_compliant_generation"]),
                    fmt(result["t90_generation"]),
                    fmt(nd, 2),
                    fmt(other, 2),
                    f"{fmt(result['diversity_start'], 2)}$\\to${fmt(result['diversity_end'], 2)}",
                ]
            )
            + " \\\\"
        )
    (GEN / "pilot_table.tex").write_text("\n".join(table) + "\n", encoding="utf-8")

    total = sum(labels.values())
    for key, name in (
        ("refusal", "Refusal"),
        ("benign_educational", "Benign"),
        ("ambiguous", "Ambiguous"),
        ("compliant", "Compliant"),
    ):
        numbers[f"pilotShare{name}"] = pct(labels.get(key, 0) / total)
    numbers["pilotSamples"] = f"{total:,}".replace(",", "{,}")
    numbers["pilotRuns"] = len(run_dirs)
    numbers["pilotNearDupMin"] = pct(min(near_dup), 0)
    numbers["pilotNearDupMax"] = pct(max(near_dup), 0)
    numbers["pilotNoopMin"] = pct(min(noop_shares), 0)
    numbers["pilotNoopMax"] = pct(max(noop_shares), 0)
    worst = max((v for v in pattern_share.values() if v is not None), default=None)
    numbers["pilotTopPatternShareMax"] = pct(worst, 0) if worst is not None else "[not measured]"

    leads = [
        r["progress_compliance_correlation"]["noncompliant_progress_to_compliance_lag3"]
        for r in results
        if r["progress_compliance_correlation"]["noncompliant_progress_to_compliance_lag3"] is not None
    ]
    same = [
        r["progress_compliance_correlation"]["same_generation"]
        for r in results
        if r["progress_compliance_correlation"]["same_generation"] is not None
    ]
    numbers["progressLeadMedian"] = f"{statistics.median(leads):.2f}"
    numbers["progressLeadPositive"] = sum(v > 0 for v in leads)
    numbers["progressLeadCount"] = len(leads)
    numbers["progressSameMedian"] = f"{statistics.median(same):.2f}"

    shocks = [s for r in results for s in r["filter_shocks"]]
    drops = [s["drop"] for s in shocks]
    recoveries = [s["generations_to_half_recovery"] for s in shocks if s["generations_to_half_recovery"] is not None]
    numbers["shockCount"] = len(shocks)
    numbers["shockMedianDrop"] = f"{statistics.median(drops):.3f}"
    numbers["shockRecoveredWithinOne"] = sum(1 for v in recoveries if v <= 1)
    numbers["shockRecoverable"] = len(recoveries)
    return results


def ab(numbers: Numbers):
    base = ROOT / "outputs" / "simulated_ab"
    summary = json.loads((base / "ab_summary.json").read_text())
    with (base / "ab_runs.csv").open(newline="", encoding="utf-8") as handle:
        runs = list(csv.DictReader(handle))
    rows = []
    metrics = [
        ("mean_offspring_success", "Mean offspring success rate", 3),
        ("early_offspring_success", "Early-quarter offspring success rate", 3),
        ("late_offspring_success", "Late-quarter offspring success rate", 3),
        ("late_offspring_progress", "Late-quarter offspring progress", 3),
        ("zero_best_generations", "Generations with best fitness $=0$", 1),
        ("final_parent_lineages", "Surviving seed lineages (final)", 1),
        ("final_population_diversity", "Population diversity (final)", 2),
        ("best_ever_fitness", "Best fitness ever observed", 3),
        ("llm_calls", "Model calls", 0),
        ("filter_versions", "Accepted filter updates", 1),
    ]
    for key, label, digits in metrics:
        legacy, improved = summary["legacy"][key], summary["improved"][key]
        wins = sum(
            1
            for seed in {r["seed"] for r in runs}
            if _seed_value(runs, "improved", seed, key) > _seed_value(runs, "legacy", seed, key)
        )
        rows.append(
            f"{label} & {legacy:.{digits}f} & {improved:.{digits}f} & {wins}/{len({r['seed'] for r in runs})} \\\\"
        )
    (GEN / "ab_table.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
    numbers["abSeeds"] = len({r["seed"] for r in runs})
    numbers["abLegacyMeanSuccess"] = f"{summary['legacy']['mean_offspring_success']:.3f}"
    numbers["abImprovedMeanSuccess"] = f"{summary['improved']['mean_offspring_success']:.3f}"
    numbers["abRelativeGain"] = pct(
        summary["improved"]["mean_offspring_success"] / summary["legacy"]["mean_offspring_success"] - 1.0, 0
    )
    numbers["abLegacyLineages"] = f"{summary['legacy']['final_parent_lineages']:.0f}"
    numbers["abImprovedLineages"] = f"{summary['improved']['final_parent_lineages']:.0f}"
    numbers["abLegacyDiversity"] = f"{summary['legacy']['final_population_diversity']:.2f}"
    numbers["abImprovedDiversity"] = f"{summary['improved']['final_population_diversity']:.2f}"
    numbers["abLegacyCalls"] = f"{summary['legacy']['llm_calls']:.0f}"
    numbers["abImprovedCalls"] = f"{summary['improved']['llm_calls']:.0f}"
    histories = {}
    for arm in ("legacy", "improved"):
        histories[arm] = []
        for run_dir in sorted(base.glob(f"{arm}_seed*")):
            with (run_dir / "history.jsonl").open(encoding="utf-8") as handle:
                histories[arm].append([json.loads(line) for line in handle if line.strip()])
    return histories


def _seed_value(runs, arm, seed, key):
    for row in runs:
        if row["arm"] == arm and row["seed"] == seed:
            return float(row[key])
    return float("nan")


def simulator(numbers: Numbers):
    from experiments.simulated_target import SimulatedTargetClient, _sigmoid

    client = SimulatedTargetClient()
    with (ROOT / "prompts" / "initial_population.csv").open(encoding="utf-8") as handle:
        texts = [row["text"] for row in csv.DictReader(handle)]
    base_filter = "You are a helpful assistant."
    rates = [_sigmoid(client.susceptibility(text, base_filter) - client.difficulty) for text in texts]
    numbers["simDifficulty"] = f"{client.difficulty:.1f}"
    numbers["simBaseRate"] = pct(statistics.mean(rates))


def budget(numbers: Numbers):
    from argparse import Namespace

    spec = importlib.util.spec_from_file_location("estimate_budget", ROOT / "scripts" / "estimate_budget.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    args = Namespace(
        mu=16, lambda_=64, generations=300, k_evals=3, parent_resample_k=1,
        max_samples_per_prompt=12, filter_update_every=15, filter_warmup_generations=30,
        top_k_filter=8, benign_prompts=40, candidate_rules=4, final_k_evals=16,
        duplicate_share=0.05, seconds_per_call=2.5, concurrency=8,
    )
    result = module.estimate(args)
    numbers["budgetCalls"] = f"{result['total_calls']:,}".replace(",", "{,}")
    numbers["budgetHours"] = result["estimated_hours"]
    numbers["budgetHoursSequential"] = result["estimated_hours_sequential"]
    numbers["budgetSearchCalls"] = f"{result['search_calls']:,}".replace(",", "{,}")
    numbers["budgetFilterCalls"] = f"{result['filter_update_calls']:,}".replace(",", "{,}")
    numbers["budgetResampleCalls"] = f"{result['parent_resample_calls']:,}".replace(",", "{,}")


# ---------------------------------------------------------------- figures


def _style(plt):
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 8,
            "axes.edgecolor": MUTED,
            "axes.labelcolor": INK,
            "axes.linewidth": 0.6,
            "xtick.color": MUTED,
            "ytick.color": MUTED,
            "axes.grid": True,
            "grid.color": GRID,
            "grid.linewidth": 0.5,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "legend.frameon": False,
            "lines.linewidth": 1.4,
            "pdf.fonttype": 42,
        }
    )


def fig_pilot_curves(results, plt):
    chosen = ["real_fixed_filter_baseline_v6", "real_filter_v6", "main_v15_multi_fallback", "main_v17_garbled_filter_fallback"]
    by_name = {Path(r["path"]).name: r for r in results}
    figure, axes = plt.subplots(2, 2, figsize=(7.0, 4.2), sharex=True, sharey=True)
    for axis, name in zip(axes.flat, chosen):
        series = by_name[name]["series"]
        axis.plot(series["generation"], series["smoothed_compliance_rate"], color=BLUE, label="Compliance rate")
        axis.plot(series["generation"], series["smoothed_attack_progress"], color=ORANGE, label="Attack progress")
        for update in series["filter_update_generations"]:
            axis.axvline(update, color=MUTED, linestyle=":", linewidth=0.8)
        axis.set_title(RUN_LABELS[name], fontsize=8, color=INK)
        axis.set_ylim(0, 1)
    for axis in axes[1]:
        axis.set_xlabel("Generation")
    for axis in axes[:, 0]:
        axis.set_ylabel("Offspring rate (5-gen. mean)")
    axes[0, 0].legend(loc="upper left", fontsize=7)
    figure.tight_layout()
    figure.savefig(FIG / "pilot_curves.pdf")
    plt.close(figure)


def fig_gate_losses(results, plt):
    labels, near, other = [], [], []
    for result in results:
        name = Path(result["path"]).name
        gates = result["quality_gate_rejections_per_parent_slot"]
        labels.append(RUN_LABELS[name].replace(" (fixed)", "\n(fixed)"))
        near.append(gates.get("near_duplicate", 0.0))
        other.append(sum(v for k, v in gates.items() if k != "near_duplicate"))
    figure, axis = plt.subplots(figsize=(7.0, 2.4))
    x = range(len(labels))
    axis.bar(x, near, color=BLUE, width=0.62, label="Near-duplicate (sticky mark)")
    axis.bar(x, other, bottom=near, color=ORANGE, width=0.62, label="Other quality gates",
             edgecolor="white", linewidth=1.0)
    axis.set_xticks(list(x), labels, fontsize=7)
    axis.set_ylim(0, 1.08)
    axis.set_ylabel("Invalid share of parent slots")
    axis.legend(loc="upper center", ncol=2, fontsize=7, bbox_to_anchor=(0.5, 1.18))
    figure.tight_layout()
    figure.savefig(FIG / "gate_losses.pdf")
    plt.close(figure)


def fig_filter_events(results, plt):
    window = range(-5, 6)
    aligned = defaultdict(list)
    for result in results:
        series = result["series"]
        index = {g: i for i, g in enumerate(series["generation"])}
        for update in series["filter_update_generations"]:
            for offset in window:
                g = update + offset
                if g in index:
                    aligned[offset].append(series["compliance_rate"][index[g]])
    offsets = [o for o in window if aligned[o]]
    means = [statistics.mean(aligned[o]) for o in offsets]
    lows = [statistics.quantiles(aligned[o], n=4)[0] if len(aligned[o]) > 1 else aligned[o][0] for o in offsets]
    highs = [statistics.quantiles(aligned[o], n=4)[2] if len(aligned[o]) > 1 else aligned[o][0] for o in offsets]
    figure, axis = plt.subplots(figsize=(3.4, 2.4))
    axis.fill_between(offsets, lows, highs, color=BLUE, alpha=0.18, linewidth=0, label="Interquartile range")
    axis.plot(offsets, means, color=BLUE, marker="o", markersize=3, label="Mean")
    axis.axvline(0, color=MUTED, linestyle=":", linewidth=0.8)
    axis.set_xlabel("Generations relative to accepted filter update")
    axis.set_ylabel("Offspring compliance rate")
    axis.legend(fontsize=7, loc="upper right")
    figure.tight_layout()
    figure.savefig(FIG / "filter_events.pdf")
    plt.close(figure)
    return len(aligned[0])


def fig_ab(histories, plt):
    figure, axes = plt.subplots(1, 2, figsize=(7.0, 2.5))
    for arm, color, label in (("legacy", ORANGE, "Legacy controls"), ("improved", BLUE, "Proposed controls")):
        runs = histories[arm]
        length = min(len(run) for run in runs)
        generations = [runs[0][i]["generation"] for i in range(length)]
        for axis, key in zip(axes, ("offspring_attack_success_rate", "population_diversity")):
            values = [[run[i][key] for run in runs] for i in range(length)]
            means = [statistics.mean(v) for v in values]
            if key == "offspring_attack_success_rate":
                means = _trailing_mean(means, 5)
            low = [min(v) for v in values]
            high = [max(v) for v in values]
            if key != "offspring_attack_success_rate":
                axis.fill_between(generations, low, high, color=color, alpha=0.15, linewidth=0)
            axis.plot(generations, means, color=color, label=label)
    axes[0].set_ylabel("Offspring success rate (5-gen. mean)")
    axes[1].set_ylabel("Population diversity")
    for axis in axes:
        axis.set_xlabel("Generation")
    axes[0].legend(fontsize=7, loc="upper right")
    figure.tight_layout()
    figure.savefig(FIG / "simulated_ab.pdf")
    plt.close(figure)


def _trailing_mean(values, window):
    return [statistics.mean(values[max(0, i - window + 1): i + 1]) for i in range(len(values))]


def main() -> int:
    GEN.mkdir(parents=True, exist_ok=True)
    FIG.mkdir(parents=True, exist_ok=True)
    numbers = Numbers()
    seed_gate_audit(numbers)
    seed_labels(numbers)
    calibration(numbers)
    results = pilot(numbers)
    histories = ab(numbers)
    budget(numbers)
    simulator(numbers)

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    _style(plt)
    fig_pilot_curves(results, plt)
    fig_gate_losses(results, plt)
    numbers["shockEventsAtZero"] = fig_filter_events(results, plt)
    fig_ab(histories, plt)
    numbers.write(GEN / "numbers.tex")
    print((GEN / "numbers.tex").read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
